<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKj8vhqs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKj8vhqs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKj8vhqs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKj8vhqs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKj8vhqs\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kj8vhqs',
    'container.build_id' => '3ad83027',
    'container.build_time' => 1541204650,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKj8vhqs');
